### PR TITLE
New sprites + shell assembler visuals

### PR DESCRIPTION
**Pull request by SteelBlue8**

### CODE REVIEW

**Comment by GlennFolker** [comment]
22 commits are you kidding. use git h

**Comment by SteelBlue8** [comment]
> 22 commits are you kidding. use git h

I have no idea what that means and yeah, I'm terrible at this but hey, it works.

**Comment by sk7725** [comment]
h

**Comment by SteelBlue8** [comment]
> h

Thanks

**Comment by sk7725** [comment]
> > h
> 
> Thanks

you're welcome



h

**Pull request merged**
