### PR TITLE
5x5 turret base

### PR DESCRIPTION
**Pull request by kapzduke**
block-5
requested by GlennFolker

### CODE REVIEW

**Comment by JerichoFletcher** [comment]
Will be merged along with branch v1.5. Thanks 👍

**Comment by kapzduke** [comment]
uhhhh i didnt mean to merge the entire 1.5 branch, idk how that happened, i just tried to create a pull request, nothing else

**Comment by JerichoFletcher** [comment]
Yea.. it's OK I guess

**Comment by kapzduke** [comment]
i figured out why "this wasn't supposed to happen", i didn't
read the guide because i only used github to download mods, so i didn't know how to compare branches, i'm gonna make another pull request

**Pull request closed without merging**
